use garde::Validate;
use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `PersistentVolumeSync` resource, directly
/// reflects context of the `persistentvolumesyncs.storage.cndev.nl` file to be found in this repository.
/// The `PersistentVolumeSync` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, Validate, Clone, Default, JsonSchema)]
#[kube(
    group = "storage.cndev.nl",
    version = "v1alpha1",
    kind = "PersistentVolumeSync",
    plural = "persistentvolumesyncs"
)]
#[kube(status = "PersistentVolumeSyncStatus")]
pub struct PersistentVolumeSyncSpec {
    #[garde(skip)]
    #[serde(rename = "protectedCluster")]
    pub protected_cluster: String,
    #[garde(skip)]
    #[serde(rename = "cloudProvider")]
    pub cloud_provider: String,
    #[garde(skip)]
    pub mode: SyncMode,
    #[garde(skip)]
    #[serde(rename = "retention")]
    pub retention: u16,
    #[garde(skip)]
    #[serde(rename = "pollingInterval")]
    pub polling_interval: Option<u64>,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, JsonSchema, Default)]
pub enum SyncMode {
    #[default]
    Protected,
    Recovery,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default, JsonSchema)]
pub struct Annotation {
    pub key: String,
    pub value: String,
}

#[derive(Deserialize, Serialize, Clone, Debug, Default, JsonSchema)]
pub struct PersistentVolumeSyncStatus {
    pub succeeded: bool,
}

/*
// status to develop further
// For example, you might want to add fields like 'last_run', 'error_message',
#[derive(Serialize, Deserialize, Clone, Debug, Default, JsonSchema)]
pub struct PersistentVolumeSyncStatus {
    pub succeeded: bool,
    pub error_message: Option<String>,
    pub last_run: Option<chrono::DateTime<chrono::Utc>>,
    pub managed_volumes: Vec<String>, // The new field
}
*/
